services:
  db:
    image: supabase/postgres:15.1.0.117
    container_name: supabase-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - ./../../supabase/migrations:/docker-entrypoint-initdb.d
      - type: bind
        source: ../../supabase/config/postgresql.conf
        target: /etc/postgresql/postgresql.conf
      - type: bind
        source: ../../supabase/config/pg_hba.conf
        target: /etc/postgresql/pg_hba.conf
      - db-data:/var/lib/postgresql/data
    command: 
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - supabase_network

networks:
  supabase_network:
    driver: bridge

volumes:
  db-data:
    name: supabase-db-data