services:
  fastapi:
    build:
      context: ../../backend
      dockerfile: Dockerfile
    container_name: fastapi-service
    restart: unless-stopped
    ports:
      - "8888:8000"  # Usamos 8888 para evitar conflictos con Supabase
    environment:
      - ENVIRONMENT=development
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_SERVICE_KEY}
      - SUPABASE_JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    volumes:
      - ../../backend:/app
    networks:
      - supabase_network
    depends_on:
      - supabase-db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

networks:
  supabase_network:
    external: true